# -*- coding: utf-8 -*-
"""Day1 Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JOk3MNihCllJPZHMHQdx801F1Sw2DnFV
"""

#Assignment - Take two inputs and store in variable X and Y, find X to the power Y.

X=2
Y=3
res=X**Y
print('X to the power Y is:'res)

