# -*- coding: utf-8 -*-
"""Day2 Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bpreSR3g0gMBgXLt8GShLke0e9Ah2cww
"""

# Take string input and find the occurrence of each characters
str = "welcome"
for ch in str:
     print(ch, str.count(ch))